[package]
name = "forge_template"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]

html-escape = "0.2.13"

[dev-dependencies]
pretty_assertions.workspace = true
