[package]
name = "forge_ci"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
gh-workflow.workspace = true
indexmap.workspace = true
derive_setters.workspace = true

[dev-dependencies]

